apiVersion: skaffold/v4beta11
kind: Config
metadata:
    name: game-app
build:
    artifacts:
        - image: game-app
          sync:
              infer:
                  - "**/*"
          docker:
              dockerfile: Dockerfile
        - image: game-app-api
          context: api
          sync:
              infer:
                  - "**/*"
          docker:
              dockerfile: Dockerfile

manifests:
    rawYaml:
        - ingress/ingress.yaml
        - k8s/deployment.yaml
        - k8s/service.yaml
