apiVersion: apps/v1
kind: Deployment
metadata:
    name: deployment-game-app
spec:
    replicas: 2
    selector:
        matchLabels:
            app: game-app

    template:
        metadata:
            labels:
                app: game-app
        spec:
            containers:
                - name: game-app
                  image: "game-app:1"
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: deployment-game-app-api
spec:
    replicas: 2
    selector:
        matchLabels:
            app: game-app-api

    template:
        metadata:
            labels:
                app: game-app-api
        spec:
            containers:
                - name: game-app-api
                  image: "game-app-api:1"
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 4000

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: deployment-game-app-mongo-api
spec:
    replicas: 1
    selector:
        matchLabels:
            app: game-app-mongo-api

    template:
        metadata:
            labels:
                app: game-app-mongo-api
        spec:
            containers:
                - name: game-app-mongo-api
                  image: "game-app-mongo-api:1"
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: deployment-game-app-mongo-db
spec:
    replicas: 1
    selector:
        matchLabels:
            app: game-app-mongo-db

    template:
        metadata:
            labels:
                app: game-app-mongo-db
        spec:
            containers:
                - name: game-app-mongo-db
                  image: "game-app-mongo-db:1"
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 27017
