apiVersion: v1
kind: Service
metadata:
    name: service-game-app
spec:
    selector:
        app: game-app
    type: NodePort
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
    name: service-game-app-api
spec:
    selector:
        app: game-app-api
    type: NodePort
    ports:
        - protocol: TCP
          port: 4000
          targetPort: 4000
