apiVersion: v1
kind: Service
metadata:
    name: service-game-app
spec:
    selector:
        app: game-app
    type: NodePort
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
    name: service-game-app-api
spec:
    selector:
        app: game-app-api
    type: NodePort
    ports:
        - protocol: TCP
          port: 4000
          targetPort: 4000

---
apiVersion: v1
kind: Service
metadata:
    name: service-game-app-mongo-api
spec:
    selector:
        app: game-app-mongo-api
    type: NodePort
    ports:
        - protocol: TCP
          port: 5000
          targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
    name: service-game-app-mongo-db
spec:
    selector:
        app: game-app-mongo-db
    type: NodePort
    ports:
        - protocol: TCP
          port: 27017
          targetPort: 27017
